<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LANSA-TEST" failures="3" tests="31" name="com.fusioncharts.testcases.OnLoadEventsTest" time="34.832" errors="1" timestamp="25 Aug 2020 12:58:25 GMT">
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="beforeExport" time="2.661"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="beforeInitialize" time="0.141"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="beforeDataUpdate" time="0.141"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="exported" time="0.176"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="renderComplete" time="0.143"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="resized" time="0.495"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="legendItemRollout" time="0.221"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="dataplotRollOut" time="0.223">
    <failure message="binValueFormatted is 0.51Â°C expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: binValueFormatted is 0.51Â°C expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.fusioncharts.events.DataPlotRollOut.dataplotrollout(DataPlotRollOut.java:68)
	at com.fusioncharts.testcases.OnLoadEventsTest.dataplotRollOut(OnLoadEventsTest.java:249)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- dataplotRollOut -->
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="dataUpdated" time="0.119"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="beforePrint" time="2.147"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="dataplotRollOver" time="1.297">
    <failure message="binValueFormatted is 0.51Â°C expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: binValueFormatted is 0.51Â°C expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.fusioncharts.events.DataPlotRollover.dataplotrollover(DataPlotRollover.java:69)
	at com.fusioncharts.testcases.OnLoadEventsTest.dataplotRollOver(OnLoadEventsTest.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- dataplotRollOver -->
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="initialized" time="0.129"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="drawComplete" time="0.128"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="ready" time="0.084"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="chartClick" time="10.175"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="beforeDraw" time="0.107"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="legendItemClicked" time="6.700"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="chartRollOver" time="0.149"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="beforeDispose" time="2.258"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="dataLoaded" time="0.092"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="dataplotClick" time="0.236">
    <failure message="binValueFormatted is 0.51Â°C expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: binValueFormatted is 0.51Â°C expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.fusioncharts.events.DataPlotClick.dataplotclick(DataPlotClick.java:68)
	at com.fusioncharts.testcases.OnLoadEventsTest.dataplotClick(OnLoadEventsTest.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- dataplotClick -->
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="chartMouseMove" time="0.198"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="beforeResize" time="5.852"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="animationInvoked" time="0.069">
    <error message="javascript error: Cannot read property &#039;eObj&#039; of undefined
  (Session info: chrome=84.0.4147.125)
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;LANSA-TEST&#039;, ip: &#039;192.168.1.102&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;13.0.2&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 84.0.4147.125, chrome: {chromedriverVersion: 84.0.4147.30 (48b3e868b4cc0..., userDataDir: C:\Users\amurthy\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:58094}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: c7d729a430819c18b65db0a858aafec2" type="org.openqa.selenium.JavascriptException">
      <![CDATA[org.openqa.selenium.JavascriptException: javascript error: Cannot read property 'eObj' of undefined
  (Session info: chrome=84.0.4147.125)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LANSA-TEST', ip: '192.168.1.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '13.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 84.0.4147.125, chrome: {chromedriverVersion: 84.0.4147.30 (48b3e868b4cc0..., userDataDir: C:\Users\amurthy\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:58094}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: c7d729a430819c18b65db0a858aafec2
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:489)
	at com.fusioncharts.events.AnimationInvoked.animationinvoked(AnimationInvoked.java:24)
	at com.fusioncharts.testcases.OnLoadEventsTest.animationInvoked(OnLoadEventsTest.java:153)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </error>
  </testcase> <!-- animationInvoked -->
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="loaded" time="0.160"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="beforeRender" time="0.138"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="printComplete" time="0.088"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="disposed" time="0.091"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="chartRollOut" time="0.159"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="legendItemRollover" time="0.161"/>
  <testcase classname="com.fusioncharts.testcases.OnLoadEventsTest" name="rendered" time="0.094"/>
</testsuite> <!-- com.fusioncharts.testcases.OnLoadEventsTest -->
